package cc.unitmesh.core.completion

/**
 * The `CompletionBuilderType` enum represents the different types of code completion that can be generated by the completion builder.
 *
 * - `INLINE_COMPLETION`: This type generates code after the cursor position. For example, if the text after `Blog blog = ` is `new Blog();`, this type will generate `new Blog();`.
 *
 * - `IN_BLOCK_COMPLETION`: This type generates the rest of the code for a correct block. It is typically used for generating code within a function or method.
 *
 * - `AFTER_BLOCK_COMPLETION`: This type generates code after a block. It is commonly used for generating multiple functions or methods.
 *
 * - `TEST_CODE_GEN`: This type generates the full code for a file. It is often used for generating test code, class code, or API code.
 *
 * - `DOCUMENTATION`: This type generates documentation for code. It is used to generate comments and documentation for classes, methods, and variables.
 */
enum class CompletionBuilderType {
    /**
     * generate code after cursor, like text after `Blog blog = `, will be `new Blog();`
     */
    INLINE_COMPLETION,

    /**
     * generate the rest of code of correct block, like function inner code
     */
    IN_BLOCK_COMPLETION,

    /**
     * generate code after block, like multiple functions
     */
    AFTER_BLOCK_COMPLETION,

    /**
     * generate full file code, like test code, class code, api code
     */
    TEST_CODE_GEN,

    /**
     * generate documentation for code
     */
    DOCUMENTATION
}