package cc.unitmesh.quality.badsmell

enum class SmellType {
    SMELL_GARPH_CONNECTED_CALL,
    SMELL_LAZY_ELEMENT,
    SMELL_LONG_METHOD,
    SMELL_DATA_CLASS,
    SMELL_REFUSED_BEQUEST,
    SMELL_LARGE_CLASS,
    SMELL_COMPLEX_CONDITION,
    SMELL_REPEATED_SWITCHES,
    SMELL_LONG_PARAMETER_LIST
}